name: RELEASE for dbt-iomete

on:
  push:
    tags:
      - 'dbt-iomete-v*' # Will only run this workflow for tags starting with dbt-iomete-v, e.g. v2.0.0...

defaults:
  run:
    working-directory: dbt-iomete

jobs:
  test:
    uses: ./.github/workflows/dbt-iomete-pr-check.yml
    secrets: inherit

  package-and-publish:
    needs: test
    runs-on: ubuntu-latest
    env:
      # Needed to publish to PyPI and to extract the version from the tag ref.
      PYPI_TOKEN: '${{ secrets.PYPI_TOKEN }}'
      REF: '${{ github.ref }}'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Set up environment
        uses: ./.github/actions/dbt-iomete-setup

      - name: Extract tags (versions)
        id: extract_tag
        shell: bash
        run: |
          NEW_TAG=${REF##*/}                                     # dbt-iomete-v2.0.0
          echo "new_version=${NEW_TAG##*-v}" >> $GITHUB_OUTPUT   # 2.0.0

      - name: Clean up dist
        run: rm -rf dist/

      - name: Create distribution
        run: python setup.py sdist

      - name: Detect if dist/ is empty
        # Pushing packages from empty directory raises an error in actions, detect if empty first
        id: check_dist
        shell: bash
        run: |
          if [[ $(ls -A "dist/" | wc -l) -ne 0 ]]
            then
              echo 'not empty' && echo "not_empty='true'" >> $GITHUB_OUTPUT
            else
              echo 'empty' && echo "not_empty='false'" >> $GITHUB_OUTPUT
          fi

      - name: Publish packages
        if: ( success() && contains(steps.check_dist.outputs.not_empty, 'true') )
        run: twine upload -u __token__ -p "$PYPI_TOKEN" dist/*

      - name: Trigger post-release workflow
        # This will check if newly published packages can be pip installed in clean environments
        if: success()
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.API_TOKEN }}
          repository: ${{ github.repository }}
          event-type: post-release
          client-payload: '{"version": "${{ steps.extract_tag.outputs.new_version }}"}'
